[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  framework = "vite"
  functionsPort = 9999

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build.environment]
  NETLIFY_ACCESS_TOKEN = "nfp_rpNQC9Tf9Vr8kBP3L3ZDGZfvRkSZdUCD13a4"
